ALTER TABLE flashcards ADD COLUMN repetitions INT DEFAULT 0 NOT NULL;
ALTER TABLE flashcards ADD COLUMN ease_factor DOUBLE PRECISION DEFAULT 2.5 NOT NULL;
ALTER TABLE flashcards ADD COLUMN interval_days INT DEFAULT 0 NOT NULL;
ALTER TABLE flashcards ADD COLUMN due_date DATE DEFAULT CURRENT_DATE NOT NULL;
ALTER TABLE flashcards ADD COLUMN last_reviewed TIMESTAMP;
